spring:
  profiles:
    default: prod

---
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${{ secrets.DB_URL }}
    port: ${{ secrets.DB_PORT }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
cloud:
  aws:
    s3:
      bucket: ${{ secrets.AWS_BUCKET }}
    stack.auto: false
    region.static: ${{ secrets.AWS_REGION }}
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.AWS_SECRET_KEY }}
---
---