server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


spring:
  profiles:
    group:
      local: local
      prod: prod
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    ssh:
      host: ec2-54-80-124-254.compute-1.amazonaws.com
      port: 22
      user: ubuntu
      keyfile: src/main/resources/portfolio-api-monitering-instance.pem
    write:
      hikari:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:[forwardedPort]/postgres
        port: 5432
        endpoint: portfolio-psql.cluster-cht7mrcxyht1.us-east-1.rds.amazonaws.com
        read-only: true
        username: postgres
        password: Tmxhfl953!
    read:
      hikari:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:[forwardedPort]/postgres
        port: 5432
        endpoint: portfolio-psql.cluster-ro-cht7mrcxyht1.us-east-1.rds.amazonaws.com
        read-only: true
        username: postgres
        password: Tmxhfl953!
---
spring:
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    write:
      hikari:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://portfolio-psql.cluster-cht7mrcxyht1.us-east-1.rds.amazonaws.com:5432/postgres
        username: postgres
        password: Tmxhfl953!
    read:
      hikari:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://portfolio-psql.cluster-ro-cht7mrcxyht1.us-east-1.rds.amazonaws.com:5432/postgres
        username: postgres
        password: Tmxhfl953!
---
