# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

env:
  AWS_REGION: "ap-northeast-2"
  ECR_REPOSITORY: "portfolio_api"
  IMAGE_TAG: latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@4

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credential@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ROLE_API_IAM }}
        aws-secret-access-key: ${{ secrets.AWS_ROLE_API_IAM_SECRET_ACCESS }}
        aws-region: ${{ env.AWS_REGION }} 
        
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Aws ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.lo.login-ecr.outputs.registry }}
      run:
        docker build -t $ECR_REPOSITORY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} .
        docker push $ECR_REPOSITORY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}"    
        
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
            
    - name: Make copy of artifacts
      run: chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh" && bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
      
    # Docker 이미지 Build (2)
    - name: docker image build
      run: docker build -t portfolio_api .
          
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit the artifacts.
